apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-user-management-configs
  namespace: django
data:
  db_name: k8s_auth
  user: k8s_auth-user
  port: "5435" # Same should be configured in service if we are using service to connect to this DB
  host: psql-user-management-service # We are using psql service name as a host, it'll be used only for flask connection

