# Generated by Django 5.1.4 on 2024-12-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='To identify whether the user email is verified or not'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_valid_user',
            field=models.BooleanField(default=False, help_text='To identify whether the user email is valid or not'),
        ),
    ]
