apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-management-pv
  labels:
    type: local-user-management-pv
  namespace: django
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"