# Generated by Django 5.1.4 on 2024-12-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_logs', '0002_userloginevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginevents',
            name='user_data',
            field=models.JSONField(blank=True, null=True, verbose_name='user details'),
        ),
    ]
