apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: user-management
  namespace: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      volumes:
        - name: user-management-django-volume
          persistentVolumeClaim:
            claimName: user-management-pvc
        - name: django-settings-config
          configMap:
            name: django-user-management-configs
      containers:
        - name: user-management
          image: krishnabelamkonda/django_user_mgmt:version_1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-user-management-secret
                  key: password
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: psql-user-management-configs
                  key: user
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: psql-user-management-configs
                  key: db_name
            - name: DB_PORT
              value: "5455"
#              valueFrom:
#                configMapKeyRef:
#                  name: psql-user-management-configs
#                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: psql-user-management-configs
                  key: host
          volumeMounts:
            - name: user-management-django-volume
              mountPath: /var/log/k8s_auth/
            - name: django-settings-config
              mountPath: /django_app/k8s_auth/local_settings.py
              subPath: settings.py  # This ensures it's mounted as a file

