apiVersion: v1
kind: Service
metadata:
  name: django-user-management-service
  namespace: django
spec:
  selector:
    app: django-app
  ports:
    - port: 8011
      targetPort: 8008
  type: NodePort
